const CONFIG = {
    titleWeb: "công chúa đừng giận tùng nữa hog là chích 1 cái nha b",
    introTitle: 'Nguyễn thị trà my ',
    introDesc: `thôi giận anh và đừng có bực mình nữa nhó `,
    btnIntro: '^^HiHi^^',
    title: 'bé cưng hết giận tùng nhó 🥰',
    desc: ' nếu hog trả lời mà thoát ra là đồng ý đó ',
    btnYes: 'dạaaaa <33',
    btnNo: 'đéo :3',
    question: 'Tại sao lại hết giận anhhh<3',
    btnReply: 'Gửi cho bạn <3',
    reply: 'tại vì iuuu anh tùng <33333333',
    mess: 'Mình biết mà 🥰. Yêu bạn nhiều nhiều 😘😘',
    messDesc: 'Tối nay 7h, mình chich nhó.',
    btnAccept: 'Okiiiii lun <3',
    messLink: https://www.facebook.com/profile.php?id=100078108201099
