const CONFIG = {
    titleWeb: "Tớ cần cậu mở trang này ",
    introTitle: '🥭🥭🥭🥭🥭Hii cậu🥭🥭🥭🥭🥭',
    introDesc: `Cậu chọn giúp tớ nha`,
    btnIntro: '^^ẤN ĐÂY^^',
    title: 'Uhmmm.....Nói ra thì cũng hơi ngại nhưng mà..... cậu đồng ý làm ngy tớ nhé... :3!',
    desc: 'Cậu chọn ikk',
    btnYes: 'Tớ đồng ý:33',
    btnNo: ' honggg iu :)))',
    question: ' sao cậu thích mình dạaaa :33',
    btnReply: 'Ấn đây',
    reply: ' tại vì cậu nhiều điểm chung giống tớ mà cũng thân thiện',
    mess: ':333 cảm ơnn cậuuu nhìu nhaaaa',
    messDesc: ' Tớ cũng thích cậu nhiều lắm á. Tham gia discord được 2 tháng mà cũng biết cậu lâu rồi bây giờ mới dám nói *hí hí ngại* :33.Giờ thì out page giúp tớ cái.',
    btnAccept: 'okeee luôn cậuuu  :33',
}   messLink:'https://www.facebook.com/messages/t/100029952212373'
