const CONFIG = {
    titleWeb: "Lecieltoyou",
    introTitle: 'Leciel',
    introDesc: `Gửi đến con nhóc đặc biệt được sinh ra trong ngày đặc biệt!,
    btnIntro: 'Nhấn vô',
    title: 'Happy birthday',
    desc: 'Chúc em luôn tự tin, thật nhiều sức khỏe, thật nhiều may mắn sẽ đến với em . Cho dù có thêm nhiều khó khăn, hay chuyện buồn nào nữa, hãy luôn nhớ - em có tôi, Leciel luôn đứng về phía em , ủng hộ em !  ',
    btnYes: 'Cảm ơn',
    btnNo: 'Không cảm ơn',
    question: 'Rõ rồi chứ?',
    btnReply: 'Em phải nói sao?!',
    reply: 'Tuân Lệnh',
    mess: 'Phải nói là " tuân lệnh" . Leciel là nhất, Leciel là số 1!',
    messDesc: 'Leciel luôn ở đây khi em cần',
    btnAccept: 'Vâng ạ!',
    messLink: 'https://www.facebook.com/HaitaniRan.Leciel',
}
